// This file is auto-generated by scripts/build-examples.ts
// Do not edit this file directly - edit the example files instead

import { exampleCodeMap } from "@/generated/example-code-map"
import { exampleHighlightedMap } from "@/generated/example-highlighted-map"
import { registryCodeMap } from "@/generated/registry-code-map"
import { registryHighlightedMap } from "@/generated/registry-highlighted-map"

export function getExampleCode(
  componentName: string,
  exampleName: string
): string {
  const key = `${componentName}-${exampleName}`
  return (
    exampleCodeMap[key] ||
    `// No code available for ${componentName}/${exampleName}`
  )
}

export function getExampleHighlightedCode(
  componentName: string,
  exampleName: string
): string {
  const key = `${componentName}-${exampleName}`
  return (
    exampleHighlightedMap[key] ||
    `<pre><code>// No code available for ${componentName}/${exampleName}</code></pre>`
  )
}

export function getRegistryCode(src: string): string {
  return (
    registryCodeMap[src] ||
    `// No code available for ${src}`
  )
}

export function getRegistryHighlightedCode(src: string): string {
  return (
    registryHighlightedMap[src] ||
    `<pre><code>// No code available for ${src}</code></pre>`
  )
}
