// This file is auto-generated by scripts/build-examples.ts
// Do not edit this file directly - edit the example files instead

import { exampleCodeMap } from "@/registry/example-code-map"
import { exampleHighlightedMap } from "@/registry/example-highlighted-map"

export function getExampleCode(
  componentName: string,
  exampleName: string
): string {
  const key = `${componentName}-${exampleName}`
  return (
    exampleCodeMap[key] ||
    `// No code available for ${componentName}/${exampleName}`
  )
}

export function getExampleHighlightedCode(
  componentName: string,
  exampleName: string
): string {
  const key = `${componentName}-${exampleName}`
  return (
    exampleHighlightedMap[key] ||
    `<pre><code>// No code available for ${componentName}/${exampleName}</code></pre>`
  )
}
