// This file is auto-generated by scripts/build-examples.ts
// Do not edit this file directly - edit the example files instead

const exampleCodeMap: Record<string, string> = {
  "button-basic": "import { Button } from \"@/components/ui/button\"\n\nexport default function BasicExample() {\n  return (\n    <div className=\"flex gap-4\">\n      <Button className=\"mix-blend-multiply\">Default Button</Button>\n      <Button variant=\"secondary\" className=\"mix-blend-multiply\">\n        Secondary Button\n      </Button>\n      <Button variant=\"ghost\">Ghost Button</Button>\n    </div>\n  )\n}\n",
  "button-variants": "import { Button } from \"@/components/ui/button\"\n\nexport default function VariantsExample() {\n  return (\n    <div className=\"flex flex-col gap-4\">\n      <div className=\"flex gap-4\">\n        <Button variant=\"default\">Primary</Button>\n        <Button variant=\"secondary\">Secondary</Button>\n        <Button variant=\"ghost\">Ghost</Button>\n      </div>\n      <div className=\"flex gap-4\">\n        <Button variant=\"default\" className=\"opacity-50 cursor-not-allowed\">\n          Primary Disabled\n        </Button>\n        <Button variant=\"secondary\" className=\"opacity-50 cursor-not-allowed\">\n          Secondary Disabled\n        </Button>\n        <Button variant=\"ghost\" className=\"opacity-50 cursor-not-allowed\">\n          Ghost Disabled\n        </Button>\n      </div>\n    </div>\n  )\n}\n",
  "button-sizes": "import { Button } from \"@/components/ui/button\"\n\nexport default function SizesExample() {\n  return (\n    <div className=\"flex items-center gap-4\">\n      <Button size=\"sm\">Small</Button>\n      <Button size=\"lg\">Large</Button>\n    </div>\n  )\n}\n",
  "box-basic": "import { Box } from \"@/components/ui/box\"\n\nexport default function BasicExample() {\n  return (\n    <div className=\"space-y-4\">\n      <Box className=\"p-4 bg-blue-100 rounded\">\n        This is a basic box with blue background\n      </Box>\n      <Box className=\"p-4 bg-gray-100 rounded border\">\n        This is a box with gray background and border\n      </Box>\n      <Box className=\"p-4 bg-green-100 rounded shadow\">\n        This is a box with green background and shadow\n      </Box>\n    </div>\n  )\n}\n",
  "box-as-element": "import { Box } from \"@/components/ui/box\"\n\nexport default function AsElementExample() {\n  return (\n    <div className=\"space-y-4\">\n      <Box as=\"section\" className=\"p-4 bg-gray-100\">\n        This box renders as a section element\n      </Box>\n      <Box as=\"article\" className=\"p-4 bg-white border rounded\">\n        This box renders as an article element\n      </Box>\n      <Box as=\"aside\" className=\"p-4 bg-yellow-100 rounded\">\n        This box renders as an aside element\n      </Box>\n      <Box as=\"header\" className=\"p-4 bg-blue-100 rounded\">\n        This box renders as a header element\n      </Box>\n    </div>\n  )\n}\n",
}

export function getExampleCode(
  componentName: string,
  exampleName: string
): string {
  const key = `${componentName}-${exampleName}`
  return (
    exampleCodeMap[key] ||
    `// No code available for ${componentName}/${exampleName}`
  )
}
