// This file is auto-generated by scripts/build-examples.ts
// Do not edit this file directly - edit the example files instead

import type { ComponentType } from "react"

export const dynamicImportMap: Record<
  string,
  () => Promise<Record<string, ComponentType>>
> = {
  "button-_demo": () => import("@/registry/examples/components/button/_demo"),
  "button-as-child": () => import("@/registry/examples/components/button/as-child"),
  "button-destructive": () => import("@/registry/examples/components/button/destructive"),
  "button-disabled": () => import("@/registry/examples/components/button/disabled"),
  "button-icon": () => import("@/registry/examples/components/button/icon"),
  "button-sizes": () => import("@/registry/examples/components/button/sizes"),
  "button-variants": () => import("@/registry/examples/components/button/variants"),
  "tabs-basic": () => import("@/registry/examples/components/tabs/basic"),
  "tooltip-basic": () => import("@/registry/examples/components/tooltip/basic"),
  "tooltip-sizes": () => import("@/registry/examples/components/tooltip/sizes"),
  "tooltip-variants": () => import("@/registry/examples/components/tooltip/variants"),
  "box-as-element": () => import("@/registry/examples/primitives/box/as-element"),
  "box-basic": () => import("@/registry/examples/primitives/box/basic"),
}

// Generate component examples map from discovered files
export const componentExamplesMap: Record<string, string[]> = {
  "button": ["_demo","as-child","destructive","disabled","icon","sizes","variants"],
  "tabs": ["basic"],
  "tooltip": ["basic","sizes","variants"],
  "box": ["as-element","basic"],
}
