// This file is auto-generated by scripts/build-examples.ts
// Do not edit this file directly - edit the example files instead

import type { ComponentType } from "react"

export const dynamicImportMap: Record<
  string,
  () => Promise<{ default: ComponentType }>
> = {
  "button-basic": () => import("@/registry/examples/components/button/basic"),
  "button-sizes": () => import("@/registry/examples/components/button/sizes"),
  "button-variants": () => import("@/registry/examples/components/button/variants"),
  "box-as-element": () => import("@/registry/examples/primitives/box/as-element"),
  "box-basic": () => import("@/registry/examples/primitives/box/basic"),
}

// Generate component examples map from discovered files
export const componentExamplesMap: Record<string, string[]> = {
  "button": ["basic","sizes","variants"],
  "box": ["as-element","basic"],
}
