// Auto-generated static registry index for zero-layout-shift component previews
// Generated by registry build system - DO NOT EDIT MANUALLY

import BoxAsElement from "./box/as-element"
import BoxBasic from "./box/basic"
import { ButtonDemo as ButtonDemo } from "./button/_demo"
import { ButtonAsChild as ButtonAsChild } from "./button/as-child"
import { DestructiveButton as ButtonDestructive } from "./button/destructive"
import { DisabledButton as ButtonDisabled } from "./button/disabled"
import { ButtonWithIcon as ButtonIcon } from "./button/icon"
import { ButtonSizes as ButtonSizes } from "./button/sizes"
import { ButtonVariants as ButtonVariants } from "./button/variants"
import TabsBasic from "./tabs/basic"
import TooltipBasic from "./tooltip/basic"
import TooltipSizes from "./tooltip/sizes"
import TooltipVariants from "./tooltip/variants"

// Static registry for immediate component rendering (no layout shift)
export const Index = {
  "box-as-element": BoxAsElement,
  "box-basic": BoxBasic,
  "button-_demo": ButtonDemo,
  "button-as-child": ButtonAsChild,
  "button-destructive": ButtonDestructive,
  "button-disabled": ButtonDisabled,
  "button-icon": ButtonIcon,
  "button-sizes": ButtonSizes,
  "button-variants": ButtonVariants,
  "tabs-basic": TabsBasic,
  "tooltip-basic": TooltipBasic,
  "tooltip-sizes": TooltipSizes,
  "tooltip-variants": TooltipVariants,
} as const

export type RegistryKey = keyof typeof Index
