// Auto-generated static registry index for zero-layout-shift component previews
// Generated by scripts/build-examples.ts - DO NOT EDIT MANUALLY

import { ButtonDemo as ButtonDemo } from "@/registry/examples/components/button/_demo"
import { ButtonAsChild as ButtonAsChild } from "@/registry/examples/components/button/as-child"
import { DestructiveButton as ButtonDestructive } from "@/registry/examples/components/button/destructive"
import { DisabledButton as ButtonDisabled } from "@/registry/examples/components/button/disabled"
import { ButtonWithIcon as ButtonIcon } from "@/registry/examples/components/button/icon"
import { ButtonSizes as ButtonSizes } from "@/registry/examples/components/button/sizes"
import { ButtonVariants as ButtonVariants } from "@/registry/examples/components/button/variants"
import TabsBasic from "@/registry/examples/components/tabs/basic"
import TooltipBasic from "@/registry/examples/components/tooltip/basic"
import TooltipSizes from "@/registry/examples/components/tooltip/sizes"
import TooltipVariants from "@/registry/examples/components/tooltip/variants"
import BoxAsElement from "@/registry/examples/primitives/box/as-element"
import BoxBasic from "@/registry/examples/primitives/box/basic"

// Static registry for immediate component rendering (no layout shift)
export const Index = {
  "button-_demo": ButtonDemo,
  "button-as-child": ButtonAsChild,
  "button-destructive": ButtonDestructive,
  "button-disabled": ButtonDisabled,
  "button-icon": ButtonIcon,
  "button-sizes": ButtonSizes,
  "button-variants": ButtonVariants,
  "tabs-basic": TabsBasic,
  "tooltip-basic": TooltipBasic,
  "tooltip-sizes": TooltipSizes,
  "tooltip-variants": TooltipVariants,
  "box-as-element": BoxAsElement,
  "box-basic": BoxBasic,
} as const

export type RegistryKey = keyof typeof Index
