import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "./globals.css"
import { WebsiteHeader } from "@/components/layout/WebsiteHeader"
import { cn } from "@/lib/utils"

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          geist.variable,
          geistMono.variable,
          "font-geist antialiased"
        )}
      >
        <div>
          <div className="flex flex-col rounded-br-3xl rounded-bl-3xl">
            <WebsiteHeader />

            <div className="min-h-screen flex flex-col">
              <div className="h-16" />

              {children}
            </div>
          </div>

          {/* <footer
            inert
            className="bg-neutral-900 h-[1.2lh] leading-[0.76] text-[calc(0.175*100vw)] text-nowrap tracking-tighter block box-border overflow-hidden"
            style={{
              clipPath: "border-box",
            }}
          >
            <div className="flex items-center justify-center fixed bottom-0 left-0 right-0 text-neutral-800">
              build it for real
            </div>
          </footer> */}
        </div>
      </body>
    </html>
  )
}
