import { promises as fs, watch } from "fs"
import path from "path"
import { CONFIG } from "../src/lib/config"
import { highlightCode } from "../src/lib/highlight-code"

// Dynamic example discovery
async function discoverExamples(): Promise<Record<string, string>> {
  const exampleFileMap: Record<string, string> = {}

  try {
    // Get all categories (components, primitives, etc.)
    const categories = await fs.readdir(CONFIG.EXAMPLES_DIR, {
      withFileTypes: true,
    })

    for (const category of categories) {
      if (!category.isDirectory()) continue

      const categoryPath = path.join(CONFIG.EXAMPLES_DIR, category.name)

      // Get all components in this category
      const components = await fs.readdir(categoryPath, { withFileTypes: true })

      for (const component of components) {
        if (!component.isDirectory()) continue

        const componentPath = path.join(categoryPath, component.name)

        // Get all example files for this component
        const examples = await fs.readdir(componentPath, {
          withFileTypes: true,
        })

        for (const example of examples) {
          if (!example.isFile() || !example.name.endsWith(".tsx")) continue

          // Generate key: component-example (without .tsx extension)
          const exampleName = example.name.replace(".tsx", "")
          const key = `${component.name}-${exampleName}`

          // Store relative path from project root
          const relativePath = path.relative(
            CONFIG.ROOT_DIR,
            path.join(componentPath, example.name)
          )

          exampleFileMap[key] = relativePath
        }
      }
    }
  } catch (error) {
    console.error("Error discovering examples:", error)
  }

  return exampleFileMap
}

async function buildExamples() {
  console.log("🔨 Building example code registry...")

  // Discover all examples dynamically
  const exampleFileMap = await discoverExamples()

  console.log(`🔍 Discovered ${Object.keys(exampleFileMap).length} examples:`)
  for (const [key, filePath] of Object.entries(exampleFileMap)) {
    console.log(`  - ${key}: ${filePath}`)
  }

  const exampleCodeMap: Record<string, string> = {}
  const exampleHighlightedMap: Record<string, string> = {}

  // Read and highlight each example file
  console.log("✨ Highlighting code examples...")
  for (const [key, filePath] of Object.entries(exampleFileMap)) {
    try {
      const fullPath = path.join(CONFIG.ROOT_DIR, filePath)
      const content = await fs.readFile(fullPath, "utf-8")
      exampleCodeMap[key] = content

      // Pre-highlight the code
      const highlighted = await highlightCode(content, "tsx")
      exampleHighlightedMap[key] = highlighted
    } catch (error) {
      console.warn(`⚠️  Could not read ${filePath}:`, error)
      exampleCodeMap[key] = `// Error loading code for ${key}`
      exampleHighlightedMap[
        key
      ] = `<pre><code>// Error loading code for ${key}</code></pre>`
    }
  }

  // Generate the raw code map file
  const rawCodeMapFile = `// This file is auto-generated by scripts/build-examples.ts
// Do not edit this file directly - edit the example files instead

export const exampleCodeMap: Record<string, string> = {
${Object.entries(exampleCodeMap)
  .map(([key, code]) => `  "${key}": ${JSON.stringify(code)},`)
  .join("\n")}
}
`

  // Generate the highlighted code map file
  const highlightedCodeMapFile = `// This file is auto-generated by scripts/build-examples.ts
// Do not edit this file directly - edit the example files instead

export const exampleHighlightedMap: Record<string, string> = {
${Object.entries(exampleHighlightedMap)
  .map(([key, html]) => `  "${key}": ${JSON.stringify(html)},`)
  .join("\n")}
}
`

  // Generate the updated code-extractor.ts file
  const codeExtractorFile = `// This file is auto-generated by scripts/build-examples.ts
// Do not edit this file directly - edit the example files instead

import { exampleCodeMap } from "@/registry/example-code-map"
import { exampleHighlightedMap } from "@/registry/example-highlighted-map"

export function getExampleCode(
  componentName: string,
  exampleName: string
): string {
  const key = \`\${componentName}-\${exampleName}\`
  return (
    exampleCodeMap[key] ||
    \`// No code available for \${componentName}/\${exampleName}\`
  )
}

export function getExampleHighlightedCode(
  componentName: string,
  exampleName: string
): string {
  const key = \`\${componentName}-\${exampleName}\`
  return (
    exampleHighlightedMap[key] ||
    \`<pre><code>// No code available for \${componentName}/\${exampleName}</code></pre>\`
  )
}
`

  // Generate the dynamic import map file
  const importMapFile = `// This file is auto-generated by scripts/build-examples.ts
// Do not edit this file directly - edit the example files instead

import type { ComponentType } from "react"

export const dynamicImportMap: Record<
  string,
  () => Promise<{ default: ComponentType }>
> = {
${Object.entries(exampleFileMap)
  .map(([key, filePath]) => {
    // Convert relative path to module import path
    const importPath = filePath.replace("src/", "@/").replace(".tsx", "")
    return `  "${key}": () => import("${importPath}"),`
  })
  .join("\n")}
}

// Generate component examples map from discovered files
export const componentExamplesMap: Record<string, string[]> = {
${(() => {
  const componentMap: Record<string, string[]> = {}

  // Group examples by component
  for (const key of Object.keys(exampleFileMap)) {
    const parts = key.split("-")
    const componentName = parts[0]
    const exampleName = parts.slice(1).join("-") // Handle multi-part example names like "as-element"
    if (!componentMap[componentName]) {
      componentMap[componentName] = []
    }
    componentMap[componentName].push(exampleName)
  }

  return Object.entries(componentMap)
    .map(
      ([component, examples]) =>
        `  "${component}": ${JSON.stringify(examples)},`
    )
    .join("\n")
})()}
}
`

  // Write the generated files
  await fs.writeFile(
    path.join(CONFIG.ROOT_DIR, "src/registry/example-code-map.ts"),
    rawCodeMapFile,
    "utf-8"
  )
  await fs.writeFile(
    path.join(CONFIG.ROOT_DIR, "src/registry/example-highlighted-map.ts"),
    highlightedCodeMapFile,
    "utf-8"
  )
  await fs.writeFile(CONFIG.CODE_EXTRACTOR_FILE, codeExtractorFile, "utf-8")
  await fs.writeFile(CONFIG.DYNAMIC_IMPORTS_FILE, importMapFile, "utf-8")

  console.log("✅ Example code registry built successfully!")
  console.log(`📝 Generated ${Object.keys(exampleCodeMap).length} examples`)
  console.log("📦 Generated dynamic import map")
  console.log("🗂️  Generated separate code map files in registry folder")

  return exampleFileMap
}

// Handle CLI arguments
const isWatchMode = process.argv.includes("--watch")

if (isWatchMode) {
  console.log("👀 Watching for changes in example files...")

  // Build initially and get the file paths
  let currentExampleFileMap: Record<string, string> = {}

  buildExamples()
    .then((fileMap) => {
      currentExampleFileMap = fileMap
      setupWatchers()
    })
    .catch(console.error)

  async function setupWatchers() {
    // Watch the examples directory for new files/folders
    watch(
      CONFIG.EXAMPLES_DIR,
      { recursive: true },
      async (eventType, filename) => {
        if (filename && filename.endsWith(".tsx")) {
          console.log(`📝 Example file changed: ${filename}`)

          // Rebuild and update watchers if new files are discovered
          const newFileMap = await buildExamples()

          // Check if we have new files that need watching
          const newFiles = Object.keys(newFileMap).filter(
            (key) => !Object.keys(currentExampleFileMap).includes(key)
          )

          if (newFiles.length > 0) {
            console.log(`🆕 Discovered ${newFiles.length} new example(s)`)
            currentExampleFileMap = newFileMap
          }
        }
      }
    )
  }
} else {
  // Run once
  buildExamples().catch(console.error)
}
